"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent

# Frontend and backend share a single repo-level .env file.
load_dotenv(REPO_ROOT / '.env')


def env_list(name, default=''):
    return [
        item.strip()
        for item in os.getenv(name, default).split(',')
        if item.strip()
    ]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r6&_l&vez*epdjzqwack4j9&m@g8@+!tu*t$9u-1eir^ns$zfs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() in ('1', 'true', 'yes')

default_allowed_hosts = '127.0.0.1,localhost' if DEBUG else ''
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', default_allowed_hosts)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Добавляем это:
    'rest_framework',   # API
    'rest_framework.authtoken',
    'knox',
    'corsheaders',      # Чтобы React мог подключаться
    'shop.apps.ShopConfig',             # Наше приложение
    'erp_analytics.apps.ErpAnalyticsConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # Добавляем это (ОБЯЗАТЕЛЬНО ПЕРЕД CommonMiddleware):
    'corsheaders.middleware.CorsMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

if os.getenv('ANALYTICS_POSTGRES_DB'):
    DATABASES['analytics'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('ANALYTICS_POSTGRES_DB'),
        'USER': os.getenv('ANALYTICS_POSTGRES_USER'),
        'PASSWORD': os.getenv('ANALYTICS_POSTGRES_PASSWORD'),
        'HOST': os.getenv('ANALYTICS_POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('ANALYTICS_POSTGRES_PORT', '5432'),
    }
else:
    DATABASES['analytics'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'analytics.sqlite3',
    }

DATABASE_ROUTERS = ['config.db_routers.AnalyticsRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Путь к собранным статическим файлам фронтенда
FRONTEND_BUILD_DIR = os.path.join(BASE_DIR.parent, 'kokossimo-frontend', 'dist')

# Добавляем статические файлы фронтенда в STATICFILES_DIRS
STATICFILES_DIRS = [
    FRONTEND_BUILD_DIR,
] if os.path.exists(FRONTEND_BUILD_DIR) else []

# ... конец файла ...

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173').rstrip('/')
default_frontend_origins = ','.join(dict.fromkeys([
    FRONTEND_URL,
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]))

# Разрешаем запросы с нашего React фронтенда
CORS_ALLOWED_ORIGINS = env_list('DJANGO_CORS_ALLOWED_ORIGINS', default_frontend_origins)

# Чтобы форма входа в админку с localhost:5173 (через proxy) не давала 403 CSRF
CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    ','.join(CORS_ALLOWED_ORIGINS),
)

# Альтернативный вариант - разрешить все локальные порты (только для разработки!)
# CORS_ALLOW_ALL_ORIGINS = True  # Раскомментируйте, если нужно разрешить все порты

# За Nginx запрос к Gunicorn приходит по HTTP — Django должен считать схему из X-Forwarded-Proto,
# чтобы build_absolute_uri() возвращал https:// для медиа-URL (иначе Mixed Content в браузере).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Настройки для загрузки картинок (товаров)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройки REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': None,  # Отключаем пагинацию по умолчанию
    'PAGE_SIZE': None,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
    ),
}

# Email (SMTP) settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
EMAIL_CODE_TTL_MINUTES = int(os.getenv('EMAIL_CODE_TTL_MINUTES', '10'))

# YooKassa (stage/prod keys are configured via .env)
YOOKASSA_SHOP_ID = os.getenv('YOOKASSA_SHOP_ID', '')
YOOKASSA_SECRET_KEY = os.getenv('YOOKASSA_SECRET_KEY', '')
YOOKASSA_RETURN_URL = os.getenv(
    'YOOKASSA_RETURN_URL',
    f'{FRONTEND_URL}/checkout/success',
)
# Код ставки НДС для позиций чека:
# 1 — без НДС, 2 — НДС 0%, 3 — НДС 10%, 4 — НДС 20%, 5 — НДС 10/110, 6 — НДС 20/120.
YOOKASSA_RECEIPT_VAT_CODE = int(os.getenv('YOOKASSA_RECEIPT_VAT_CODE', '1'))
_raw_tax_system_code = (os.getenv('YOOKASSA_RECEIPT_TAX_SYSTEM_CODE', '') or '').strip()
# Система налогообложения для чека (1..6). При фискализации/проверке чеков в ЮKassa обычно обязательна.
YOOKASSA_RECEIPT_TAX_SYSTEM_CODE = int(_raw_tax_system_code) if _raw_tax_system_code.isdigit() else None

# Telegram-бот для обратной связи (отзывы, предложения, просьбы о связи)
# Токен создаётся у @BotFather. Запуск: python manage.py run_telegram_bot
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')

# CDEK (PVZ map widget) service credentials
# Used by frontend widget to proxy requests to CDEK API v2.
CDEK_CLIENT_ID = os.getenv('CDEK_CLIENT_ID', '')
CDEK_CLIENT_SECRET = os.getenv('CDEK_CLIENT_SECRET', '')
CDEK_API_BASE_URL = os.getenv('CDEK_API_BASE_URL', 'https://api.cdek.ru/v2')

# МойСклад API settings
MOYSKLAD_API_BASE_URL = os.getenv('MOYSKLAD_API_BASE_URL', 'https://api.moysklad.ru/api/remap/1.2')
MOYSKLAD_TOKEN = os.getenv('MOYSKLAD_TOKEN', '')
MOYSKLAD_LOGIN = os.getenv('MOYSKLAD_LOGIN', '')
MOYSKLAD_PASSWORD = os.getenv('MOYSKLAD_PASSWORD', '')
MOYSKLAD_TIMEOUT_SECONDS = int(os.getenv('MOYSKLAD_TIMEOUT_SECONDS', '15'))
MOYSKLAD_MAX_RETRIES = int(os.getenv('MOYSKLAD_MAX_RETRIES', '3'))
MOYSKLAD_RETRY_DELAY_SECONDS = float(os.getenv('MOYSKLAD_RETRY_DELAY_SECONDS', '1.5'))
MOYSKLAD_SITE_SYNC_ENABLED = os.getenv('MOYSKLAD_SITE_SYNC_ENABLED', 'true').lower() in ('1', 'true', 'yes')
MOYSKLAD_SITE_CATEGORY_NAME = os.getenv('MOYSKLAD_SITE_CATEGORY_NAME', 'САЙТ КОКОССИМО')
MOYSKLAD_SITE_CATEGORY_SLUG = os.getenv('MOYSKLAD_SITE_CATEGORY_SLUG', 'site-kokossimo')
MOYSKLAD_SITE_CATEGORY_ID = os.getenv('MOYSKLAD_SITE_CATEGORY_ID', '')
MOYSKLAD_SITE_CATEGORY_EXTERNAL_CODE = os.getenv('MOYSKLAD_SITE_CATEGORY_EXTERNAL_CODE', '')
MOYSKLAD_SYNC_INTERVAL_SECONDS = int(os.getenv('MOYSKLAD_SYNC_INTERVAL_SECONDS', '300'))
MOYSKLAD_SYNC_RETRY_INTERVAL_SECONDS = int(os.getenv('MOYSKLAD_SYNC_RETRY_INTERVAL_SECONDS', '120'))
MOYSKLAD_VERIFY_SSL = os.getenv('MOYSKLAD_VERIFY_SSL', 'true').lower() in ('1', 'true', 'yes')
MOYSKLAD_USE_FOLDER_TREE_FILTER = os.getenv('MOYSKLAD_USE_FOLDER_TREE_FILTER', 'false').lower() in ('1', 'true', 'yes')
MOYSKLAD_RELAX_FOLDER_FILTER = os.getenv('MOYSKLAD_RELAX_FOLDER_FILTER', 'true').lower() in ('1', 'true', 'yes')
MOYSKLAD_STRICT_CATEGORY_ONLY = os.getenv('MOYSKLAD_STRICT_CATEGORY_ONLY', 'true').lower() in ('1', 'true', 'yes')
MOYSKLAD_IMAGE_META_FETCH = os.getenv('MOYSKLAD_IMAGE_META_FETCH', 'true').lower() in ('1', 'true', 'yes')
MOYSKLAD_IMAGE_PROXY_REDIRECT_ONLY = os.getenv('MOYSKLAD_IMAGE_PROXY_REDIRECT_ONLY', 'false').lower() in ('1', 'true', 'yes')
MOYSKLAD_SYNC_SAVE_LOCAL_IMAGES = os.getenv('MOYSKLAD_SYNC_SAVE_LOCAL_IMAGES', 'false').lower() in ('1', 'true', 'yes')
MOYSKLAD_SYNC_PAGE_SIZE = int(os.getenv('MOYSKLAD_SYNC_PAGE_SIZE', '50'))
MOYSKLAD_USE_SEARCH_FILTER = os.getenv('MOYSKLAD_USE_SEARCH_FILTER', 'true').lower() in ('1', 'true', 'yes')
MOYSKLAD_SITE_SEARCH_QUERY = os.getenv('MOYSKLAD_SITE_SEARCH_QUERY', '')
MOYSKLAD_SYNC_MAX_PAGES = int(os.getenv('MOYSKLAD_SYNC_MAX_PAGES', '500'))

# OpenAI для категоризации товаров (подкатегория по названию/описанию)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_CATEGORIZE_ENABLED = os.getenv('OPENAI_CATEGORIZE_ENABLED', 'true').lower() in ('1', 'true', 'yes')
OPENAI_CATEGORIZE_MODEL = os.getenv('OPENAI_CATEGORIZE_MODEL', 'gpt-4o-mini')
