# Generated by Django 6.0.1 on 2026-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_specs_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmation_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='ID платежа провайдера'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Платежный провайдер'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплата подтверждена'), ('canceled', 'Оплата отменена')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Наличными курьеру'), ('cash_pickup', 'На кассе при самовывозе'), ('yookassa', 'Онлайн-оплата (ЮKassa)')], default='cash_on_delivery', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
