# Generated by Django 6.0.1 on 2026-04-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_saveddeliveryaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuthToken',
        ),
    ]
