# Generated by Django 6.0.1 on 2026-05-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_delete_userauthtoken'),
        ('shop', '0031_order_awaiting_payment_status'),
    ]

    operations = [
    ]
