# Generated by Django 6.0.1 on 2026-05-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_merge_20260505_1254'),
    ]

    operations = [
    ]
