# Generated by Django 6.0.1 on 2026-05-07 20:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20260507_2050'),
    ]

    operations = [
    ]
