# Generated by Django 6.0.1 on 2026-05-13 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_certificate_status_labels_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'certificate',
                    models.ForeignKey(
                        blank=True,
                        db_column='certificate_id',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='transactions',
                        to='shop.certificate',
                        verbose_name='Сертификат',
                    ),
                ),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип операции')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Остаток до')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Остаток после')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='Заказ (id)')),
                ('payment_id', models.IntegerField(blank=True, null=True, verbose_name='Платёж (id)')),
                ('store_id', models.IntegerField(blank=True, null=True, verbose_name='Магазин (id)')),
                ('cash_register_id', models.IntegerField(blank=True, null=True, verbose_name='Касса (id)')),
                ('channel', models.IntegerField(blank=True, null=True, verbose_name='Канал')),
                ('performed_by', models.IntegerField(blank=True, null=True, verbose_name='Кто выполнил (user id)')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина')),
                ('idempotency_key', models.CharField(max_length=255, verbose_name='Ключ идемпотентности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
            ],
            options={
                'verbose_name': 'Операция по сертификату',
                'verbose_name_plural': 'Операции по сертификатам',
                'db_table': 'certificate_transactions',
                'ordering': ['-created_at', '-id'],
                'managed': False,
            },
        ),
    ]
